# Problem Sheet 2


In this problem sheet, you are expected to 
- Understand the notion of credit risk;
- Import the datas from either online/local data source;
- Perform basic classification of credit risk based on customer data and payment data;
- Evaluate the performance using appropriate measure;
- Practice SVM by using different kernels

### Question 1 : Data Importation 

1. Import the credit risk data (customer_data.csv) and (payment_data.csv) as pandas Dataframe into your notebook, from the source Dataset: https://www.kaggle.com/praveengovi/credit-risk-classification-dataset, name the customer data as "customer_data".

In [1]:
import pandas as pd
customer_data = pd.read_csv('./customer_data.csv')
payment_data = pd.read_csv('./payment_data.csv')

In [2]:
customer_data

label        id  fea_1   fea_2  fea_3     fea_4  fea_5  fea_6  fea_7  \
0         1  54982665      5  1245.5      3   77000.0      2     15      5   
1         0  59004779      4  1277.0      1  113000.0      2      8     -1   
2         0  58990862      7  1298.0      1  110000.0      2     11     -1   
3         1  58995168      7  1335.5      1  151000.0      2     11      5   
4         0  54987320      7     NaN      2   59000.0      2     11      5   
...     ...       ...    ...     ...    ...       ...    ...    ...    ...   
1120      0  58988196      5  1289.0      1  173000.0      2     15      5   
1121      0  58987926      5     NaN      2   50000.0      2     15      5   
1122      0  58995381      7  1220.0      3   76000.0      2     11      2   
1123      0  58998054      4  1250.0      3  137000.0      2      8      5   
1124      0  54989781      4  1415.0      3   93000.0      2      8      5   

      fea_8  fea_9  fea_10      fea_11  
0       109      5  151300  244.948974  
1       100      3  341759  207.173840  
2       101      5   72001    1.000000  
3       110      3   60084    1.000000  
4       108      4  450081  197.403141  
...     ...    ...     ...         ...  
1120    112      3  350702  200.000000  
1121    108      4  450000  169.000000  
1122     90      5   71002    1.000000  
1123     90      5   72000    1.000000  
1124    113      4  151300  273.861279  

[1125 rows x 13 columns]

In [3]:
payment_data

id  OVD_t1  OVD_t2  OVD_t3  OVD_sum  pay_normal  prod_code  \
0     58987402       0       0       0        0           1         10   
1     58995151       0       0       0        0           1          5   
2     58997200       0       0       0        0           2          5   
3     54988608       0       0       0        0           3         10   
4     54987763       0       0       0        0           2         10   
...        ...     ...     ...     ...      ...         ...        ...   
8245  58995478       0       0       0        0           9         15   
8246  54992408       0       0       0        0           1          2   
8247  54988209       0       0       0        0           5         13   
8248  54992408       0       0       0        0           1          2   
8249  54989207       0       0       0        0           1          5   

      prod_limit update_date  new_balance  highest_balance report_date  
0        16500.0  04/12/2016          0.0              NaN         NaN  
1            NaN  04/12/2016     588720.0         491100.0         NaN  
2            NaN  04/12/2016     840000.0         700500.0  22/04/2016  
3        37400.0  03/12/2016       8425.2           7520.0  25/04/2016  
4            NaN  03/12/2016      15147.6              NaN  26/04/2016  
...          ...         ...          ...              ...         ...  
8245         NaN         NaN          0.0              NaN         NaN  
8246         NaN         NaN          0.0              NaN         NaN  
8247         NaN         NaN      20654.4          33315.0         NaN  
8248         NaN         NaN          0.0              NaN         NaN  
8249         NaN         NaN     240000.0         200500.0         NaN  

[8250 rows x 12 columns]

### Question 2 : Preparation


2. How many features are there in customer_data? 

In [4]:
customer_data.size

14625

3. Find the number of customers whose label = 0. (identified as the potential defaulted customer.)

In [5]:
customer_data[customer_data['label'] == 0]

label        id  fea_1   fea_2  fea_3     fea_4  fea_5  fea_6  fea_7  \
1         0  59004779      4  1277.0      1  113000.0      2      8     -1   
2         0  58990862      7  1298.0      1  110000.0      2     11     -1   
4         0  54987320      7     NaN      2   59000.0      2     11      5   
5         0  59005995      6  1217.0      3   56000.0      2      6     -1   
8         0  58984557      5  1323.5      3  218000.0      2     15      5   
...     ...       ...    ...     ...    ...       ...    ...    ...    ...   
1120      0  58988196      5  1289.0      1  173000.0      2     15      5   
1121      0  58987926      5     NaN      2   50000.0      2     15      5   
1122      0  58995381      7  1220.0      3   76000.0      2     11      2   
1123      0  58998054      4  1250.0      3  137000.0      2      8      5   
1124      0  54989781      4  1415.0      3   93000.0      2      8      5   

      fea_8  fea_9  fea_10      fea_11  
1       100      3  341759  207.173840  
2       101      5   72001    1.000000  
4       108      4  450081  197.403141  
5       100      3   60091    1.000000  
8       112      4  151300  282.842713  
...     ...    ...     ...         ...  
1120    112      3  350702  200.000000  
1121    108      4  450000  169.000000  
1122     90      5   71002    1.000000  
1123     90      5   72000    1.000000  
1124    113      4  151300  273.861279  

[900 rows x 13 columns]

4. using the sklearn to perform data imputation and data scaling for the feature data.

In [6]:
customer_data[customer_data.isna().any(axis=1)]

label        id  fea_1  fea_2  fea_3     fea_4  fea_5  fea_6  fea_7  \
4         0  54987320      7    NaN      2   59000.0      2     11      5   
9         0  54990497      4    NaN      2   35000.0      2      8      5   
13        0  59003965      4    NaN      2   76000.0      2      8      9   
19        1  59000383      4    NaN      2   47000.0      2      8      9   
20        0  58994740      7    NaN      2   77000.0      2     11      9   
...     ...       ...    ...    ...    ...       ...    ...    ...    ...   
1105      1  59004235      4    NaN      2  150000.0      2      8      5   
1107      0  58985785      5    NaN      3  250000.0      2     15     -1   
1108      0  59003741      4    NaN      2   39000.0      2      8      5   
1117      0  59001031      4    NaN      2   58000.0      2      8      5   
1121      0  58987926      5    NaN      2   50000.0      2     15      5   

      fea_8  fea_9  fea_10      fea_11  
4       108      4  450081  197.403141  
9       101      3   60029  237.301496  
13      113      4   60091  158.407702  
19      107      5  151300    1.000000  
20      114      5  510000  159.699718  
...     ...    ...     ...         ...  
1105    100      3   60018  244.754979  
1107    111      5  450031  187.082869  
1108     90      3   60001  153.267740  
1117    100      5  151300  196.214169  
1121    108      4  450000  169.000000  

[149 rows x 13 columns]

In [7]:
from sklearn.impute import SimpleImputer
import numpy as np
imp=SimpleImputer(missing_values=np.nan,strategy='median')
imp.fit(customer_data)
X = imp.transform(customer_data)
X

array([[1.00000000e+00, 5.49826650e+07, 5.00000000e+00, ...,
        5.00000000e+00, 1.51300000e+05, 2.44948974e+02],
       [0.00000000e+00, 5.90047790e+07, 4.00000000e+00, ...,
        3.00000000e+00, 3.41759000e+05, 2.07173840e+02],
       [0.00000000e+00, 5.89908620e+07, 7.00000000e+00, ...,
        5.00000000e+00, 7.20010000e+04, 1.00000000e+00],
       ...,
       [0.00000000e+00, 5.89953810e+07, 7.00000000e+00, ...,
        5.00000000e+00, 7.10020000e+04, 1.00000000e+00],
       [0.00000000e+00, 5.89980540e+07, 4.00000000e+00, ...,
        5.00000000e+00, 7.20000000e+04, 1.00000000e+00],
       [0.00000000e+00, 5.49897810e+07, 4.00000000e+00, ...,
        4.00000000e+00, 1.51300000e+05, 2.73861279e+02]])

In [8]:
customer_data_tr = pd.DataFrame(X, columns=customer_data.columns, index=customer_data.index)
customer_data_tr

label          id  fea_1   fea_2  fea_3     fea_4  fea_5  fea_6  fea_7  \
0       1.0  54982665.0    5.0  1245.5    3.0   77000.0    2.0   15.0    5.0   
1       0.0  59004779.0    4.0  1277.0    1.0  113000.0    2.0    8.0   -1.0   
2       0.0  58990862.0    7.0  1298.0    1.0  110000.0    2.0   11.0   -1.0   
3       1.0  58995168.0    7.0  1335.5    1.0  151000.0    2.0   11.0    5.0   
4       0.0  54987320.0    7.0  1281.5    2.0   59000.0    2.0   11.0    5.0   
...     ...         ...    ...     ...    ...       ...    ...    ...    ...   
1120    0.0  58988196.0    5.0  1289.0    1.0  173000.0    2.0   15.0    5.0   
1121    0.0  58987926.0    5.0  1281.5    2.0   50000.0    2.0   15.0    5.0   
1122    0.0  58995381.0    7.0  1220.0    3.0   76000.0    2.0   11.0    2.0   
1123    0.0  58998054.0    4.0  1250.0    3.0  137000.0    2.0    8.0    5.0   
1124    0.0  54989781.0    4.0  1415.0    3.0   93000.0    2.0    8.0    5.0   

      fea_8  fea_9    fea_10      fea_11  
0     109.0    5.0  151300.0  244.948974  
1     100.0    3.0  341759.0  207.173840  
2     101.0    5.0   72001.0    1.000000  
3     110.0    3.0   60084.0    1.000000  
4     108.0    4.0  450081.0  197.403141  
...     ...    ...       ...         ...  
1120  112.0    3.0  350702.0  200.000000  
1121  108.0    4.0  450000.0  169.000000  
1122   90.0    5.0   71002.0    1.000000  
1123   90.0    5.0   72000.0    1.000000  
1124  113.0    4.0  151300.0  273.861279  

[1125 rows x 13 columns]

In [9]:
from sklearn.preprocessing import StandardScaler
scaler_std = StandardScaler()
customerD_scaled_std = scaler_std.fit_transform(customer_data_tr)
customerD_scaled_std

array([[ 2.        , -1.57134806, -0.34906978, ...,  0.94054215,
        -0.0873615 ,  0.97675366],
       [-0.5       ,  0.64305469, -1.07228064, ..., -1.39782231,
         1.16193758,  0.64117375],
       [-0.5       ,  0.63539259,  1.09735195, ...,  0.94054215,
        -0.60751632, -1.19039612],
       ...,
       [-0.5       ,  0.63788056,  1.09735195, ...,  0.94054215,
        -0.61406917, -1.19039612],
       [-0.5       ,  0.6393522 , -1.07228064, ...,  0.94054215,
        -0.60752288, -1.19039612],
       [-0.5       , -1.5674303 , -1.07228064, ..., -0.22864008,
        -0.0873615 ,  1.23359956]])

In [10]:
customerD_std = pd.DataFrame(customerD_scaled_std, columns=customer_data.columns, index=customer_data.index)
customerD_std

label        id     fea_1     fea_2     fea_3     fea_4     fea_5  \
0       2.0 -1.571348 -0.349070 -0.790346  0.758971 -0.496387  0.276686   
1      -0.5  0.643055 -1.072281 -0.136773 -1.517942 -0.089175  0.276686   
2      -0.5  0.635393  1.097352  0.298942 -1.517942 -0.123109  0.276686   
3       2.0  0.637763  1.097352  1.077005 -1.517942  0.340661  0.276686   
4      -0.5 -1.568785  1.097352 -0.043406 -0.379485 -0.699993  0.276686   
...     ...       ...       ...       ...       ...       ...       ...   
1120   -0.5  0.633925 -0.349070  0.112207 -1.517942  0.589513  0.276686   
1121   -0.5  0.633776 -0.349070 -0.043406 -0.379485 -0.801797  0.276686   
1122   -0.5  0.637881  1.097352 -1.319429  0.758971 -0.507699  0.276686   
1123   -0.5  0.639352 -1.072281 -0.696978  0.758971  0.182301  0.276686   
1124   -0.5 -1.567430 -1.072281  2.726499  0.758971 -0.315404  0.276686   

         fea_6     fea_7     fea_8     fea_9    fea_10    fea_11  
0     1.543035  0.056269  0.684045  0.940542 -0.087361  0.976754  
1    -1.073546 -1.964028 -0.066980 -1.397822  1.161938  0.641174  
2     0.047846 -1.964028  0.016467  0.940542 -0.607516 -1.190396  
3     0.047846  0.056269  0.767492 -1.397822 -0.685685 -1.190396  
4     0.047846  0.056269  0.600597 -0.228640  1.872466  0.554375  
...        ...       ...       ...       ...       ...       ...  
1120  1.543035  0.056269  0.934386 -1.397822  1.220598  0.577444  
1121  1.543035  0.056269  0.600597 -0.228640  1.871935  0.302052  
1122  0.047846 -0.953879 -0.901452  0.940542 -0.614069 -1.190396  
1123 -1.073546  0.056269 -0.901452  0.940542 -0.607523 -1.190396  
1124 -1.073546  0.056269  1.017833 -0.228640 -0.087361  1.233600  

[1125 rows x 13 columns]

### Question 3 : Binary Classification



5. Build a linear model using cross validation (3-folds), taking accuracy as the criteria, and show the score.

In [11]:
x,y = customerD_std.iloc[:,2:], customerD_std.iloc[:,0]

In [12]:
x

fea_1     fea_2     fea_3     fea_4     fea_5     fea_6     fea_7  \
0    -0.349070 -0.790346  0.758971 -0.496387  0.276686  1.543035  0.056269   
1    -1.072281 -0.136773 -1.517942 -0.089175  0.276686 -1.073546 -1.964028   
2     1.097352  0.298942 -1.517942 -0.123109  0.276686  0.047846 -1.964028   
3     1.097352  1.077005 -1.517942  0.340661  0.276686  0.047846  0.056269   
4     1.097352 -0.043406 -0.379485 -0.699993  0.276686  0.047846  0.056269   
...        ...       ...       ...       ...       ...       ...       ...   
1120 -0.349070  0.112207 -1.517942  0.589513  0.276686  1.543035  0.056269   
1121 -0.349070 -0.043406 -0.379485 -0.801797  0.276686  1.543035  0.056269   
1122  1.097352 -1.319429  0.758971 -0.507699  0.276686  0.047846 -0.953879   
1123 -1.072281 -0.696978  0.758971  0.182301  0.276686 -1.073546  0.056269   
1124 -1.072281  2.726499  0.758971 -0.315404  0.276686 -1.073546  0.056269   

         fea_8     fea_9    fea_10    fea_11  
0     0.684045  0.940542 -0.087361  0.976754  
1    -0.066980 -1.397822  1.161938  0.641174  
2     0.016467  0.940542 -0.607516 -1.190396  
3     0.767492 -1.397822 -0.685685 -1.190396  
4     0.600597 -0.228640  1.872466  0.554375  
...        ...       ...       ...       ...  
1120  0.934386 -1.397822  1.220598  0.577444  
1121  0.600597 -0.228640  1.871935  0.302052  
1122 -0.901452  0.940542 -0.614069 -1.190396  
1123 -0.901452  0.940542 -0.607523 -1.190396  
1124  1.017833 -0.228640 -0.087361  1.233600  

[1125 rows x 11 columns]

In [13]:
y

0       2.0
1      -0.5
2      -0.5
3       2.0
4      -0.5
       ... 
1120   -0.5
1121   -0.5
1122   -0.5
1123   -0.5
1124   -0.5
Name: label, Length: 1125, dtype: float64

In [14]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [11]:
# y[1]

-0.49999999999999994

In [15]:
y_train_0 = (y_train == -0.49999999999999994)
y_test_0 = (y_test == -0.49999999999999994)
print(y_train_0)

570      True
875      True
712     False
554      True
688      True
        ...  
466      True
121      True
1044     True
1095     True
860     False
Name: label, Length: 900, dtype: bool


In [16]:
from sklearn.linear_model import SGDClassifier
sgd_clf = SGDClassifier(random_state=42)
sgd_clf.fit(x_train, y_train_0)

SGDClassifier(random_state=42)

In [17]:
from sklearn.model_selection import cross_val_score
cross_val_score(sgd_clf, x_train, y_train_0, cv=3, scoring="accuracy")

array([0.69      , 0.7       , 0.79333333])

In [23]:
# cross_val_score(sgd_clf, x_test, y_test_0, cv=3, scoring="accuracy")

array([0.56      , 0.69333333, 0.69333333])

6. Find the confusion matrix, the recall and precision of the model prediction. Is the performance satisfactory?

In [18]:
from sklearn.model_selection import cross_val_predict
y_train_pred = cross_val_predict(sgd_clf, x_train, y_train_0, cv=3)

In [19]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_train_0, y_train_pred)

array([[ 32, 140],
       [105, 623]], dtype=int64)

In [28]:
# y_train_perfect_predictions = y_train_0
# confusion_matrix(y_train_0, y_train_perfect_predictions)

array([[172,   0],
       [  0, 728]], dtype=int64)

In [20]:
from sklearn.metrics import precision_score, recall_score
precision_score(y_train_0, y_train_pred)

0.8165137614678899

In [21]:
recall_score(y_train_0, y_train_pred)

0.8557692307692307

In [ ]:
# Yes.

### Question 4 : Support Vector Machine




7. Train a SVM with polynomial kernal and Gaussian RBF kernel (with cross-validation). Does that improve the result or not? 

In [22]:
y,x=np.split(customerD_std,indices_or_sections=(1,),axis=1)
x=x.iloc[:,1:12]

In [23]:
x

fea_1     fea_2     fea_3     fea_4     fea_5     fea_6     fea_7  \
0    -0.349070 -0.790346  0.758971 -0.496387  0.276686  1.543035  0.056269   
1    -1.072281 -0.136773 -1.517942 -0.089175  0.276686 -1.073546 -1.964028   
2     1.097352  0.298942 -1.517942 -0.123109  0.276686  0.047846 -1.964028   
3     1.097352  1.077005 -1.517942  0.340661  0.276686  0.047846  0.056269   
4     1.097352 -0.043406 -0.379485 -0.699993  0.276686  0.047846  0.056269   
...        ...       ...       ...       ...       ...       ...       ...   
1120 -0.349070  0.112207 -1.517942  0.589513  0.276686  1.543035  0.056269   
1121 -0.349070 -0.043406 -0.379485 -0.801797  0.276686  1.543035  0.056269   
1122  1.097352 -1.319429  0.758971 -0.507699  0.276686  0.047846 -0.953879   
1123 -1.072281 -0.696978  0.758971  0.182301  0.276686 -1.073546  0.056269   
1124 -1.072281  2.726499  0.758971 -0.315404  0.276686 -1.073546  0.056269   

         fea_8     fea_9    fea_10    fea_11  
0     0.684045  0.940542 -0.087361  0.976754  
1    -0.066980 -1.397822  1.161938  0.641174  
2     0.016467  0.940542 -0.607516 -1.190396  
3     0.767492 -1.397822 -0.685685 -1.190396  
4     0.600597 -0.228640  1.872466  0.554375  
...        ...       ...       ...       ...  
1120  0.934386 -1.397822  1.220598  0.577444  
1121  0.600597 -0.228640  1.871935  0.302052  
1122 -0.901452  0.940542 -0.614069 -1.190396  
1123 -0.901452  0.940542 -0.607523 -1.190396  
1124  1.017833 -0.228640 -0.087361  1.233600  

[1125 rows x 11 columns]

In [24]:
y

label
0       2.0
1      -0.5
2      -0.5
3       2.0
4      -0.5
...     ...
1120   -0.5
1121   -0.5
1122   -0.5
1123   -0.5
1124   -0.5

[1125 rows x 1 columns]

In [25]:
train_data,test_data,train_label,test_label =train_test_split(x,y,random_state=12,train_size=0.6,test_size=0.4)
train_label=np.array(train_label).ravel().astype('str')
test_label=np.array(test_label).ravel().astype('str')

In [26]:
from sklearn import svm
rbf_clf=svm.SVC(C=1,kernel='rbf',gamma=10,decision_function_shape='ovr')
rbf_clf.fit(train_data,train_label)
cross_val_score(rbf_clf, train_data, train_label, cv=3, scoring="accuracy")

array([0.79111111, 0.79111111, 0.78666667])

In [27]:
poly_clf=svm.SVC(C=1,kernel='poly',gamma=10,decision_function_shape='ovr')
poly_clf.fit(train_data,train_label)
cross_val_score(poly_clf, train_data, train_label, cv=3, scoring="accuracy")

array([0.63111111, 0.64444444, 0.57333333])

In [ ]:
# It didn't improve the result.

### Question 5: 
8. Now use the information from the payment data in another csv file, and try to see if that helps improve the classification performance. (You have the freedom to choose linear or nonlinear models).

In [28]:
payment_data

id  OVD_t1  OVD_t2  OVD_t3  OVD_sum  pay_normal  prod_code  \
0     58987402       0       0       0        0           1         10   
1     58995151       0       0       0        0           1          5   
2     58997200       0       0       0        0           2          5   
3     54988608       0       0       0        0           3         10   
4     54987763       0       0       0        0           2         10   
...        ...     ...     ...     ...      ...         ...        ...   
8245  58995478       0       0       0        0           9         15   
8246  54992408       0       0       0        0           1          2   
8247  54988209       0       0       0        0           5         13   
8248  54992408       0       0       0        0           1          2   
8249  54989207       0       0       0        0           1          5   

      prod_limit update_date  new_balance  highest_balance report_date  
0        16500.0  04/12/2016          0.0              NaN         NaN  
1            NaN  04/12/2016     588720.0         491100.0         NaN  
2            NaN  04/12/2016     840000.0         700500.0  22/04/2016  
3        37400.0  03/12/2016       8425.2           7520.0  25/04/2016  
4            NaN  03/12/2016      15147.6              NaN  26/04/2016  
...          ...         ...          ...              ...         ...  
8245         NaN         NaN          0.0              NaN         NaN  
8246         NaN         NaN          0.0              NaN         NaN  
8247         NaN         NaN      20654.4          33315.0         NaN  
8248         NaN         NaN          0.0              NaN         NaN  
8249         NaN         NaN     240000.0         200500.0         NaN  

[8250 rows x 12 columns]

In [29]:
X,y = payment_data.iloc[:,1:6], payment_data.iloc[:,6]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=25)

In [32]:
from sklearn.ensemble import RandomForestClassifier
rf_clf = RandomForestClassifier(n_estimators = 30)
rf_clf.fit(X_train, y_train)
y_pred = rf_clf.predict(X_test)

In [33]:
from sklearn import metrics
metrics.accuracy_score(y_test, y_pred)

0.5378787878787878

#### Remark: It is known that, according to the data provider,  most features in the customer information data are encoded via the demographic information,  instead of their financial situation.